### ISSUE TITLE
Herd Feedback

### ISSUE THREAD

**Issue by natepill** [NinjaAung/Herd_Immunity_Simulation#1]
Simulation **does not end** for following script:
```python3 simulation.py 100 0.00 Ebola 1.00 0.00 10```
I had to remove ```self``` as a positional argument in order to run your simulation.py on line 149
 Your logger file is writing errors to the file:
```
[Fail]: 23bd781d-5986-44a5-998f-d52f9df43e3c : e5cd8fa5-b31f-400e-98ec-5729980105aa is [SICK]
	[Fail]: 23bd781d-5986-44a5-998f-d52f9df43e3c : 16310b62-8811-449b-94c9-ecaae77aa78a is [SICK]
	[Fail]: 23bd781d-5986-44a5-998f-d52f9df43e3c : 16310b62-8811-449b-94c9-ecaae77aa78a is [SICK]
	[Fail]: 23bd781d-5986-44a5-998f-d52f9df43e3c : e5cd8fa5-b31f-400e-98ec-5729980105aa is [SICK]
	[Fail]: 23bd781d-5986-44a5-998f-d52f9df43e3c : 16310b62-8811-449b-94c9-ecaae77aa78a is [SICK]
```

Person class: 1/4 tests are failing
I did not see unit tests for the Simulation class
Virus test passing

**Comment by NinjaAung** [comment]
Sorry there was a merge conflict I overlooked while I was peer coding which resulted in a failure to produce a *.txt file, could you please check again
